# _*_ coding:utf-8 _*_
from selenium import webdriver
from appium import webdriver
import unittest,time,re
from time import sleep
import os

import HTMLTestRunner

class LoginTest(unittest.TestCase):
    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = '4.4.2'
        desired_caps['deviceName'] = 'test'  # 连接多个设备才有用
        # desired_caps['app'] = r'e:\apk\toutiao.apk'#如果已经安装好软件乐意不需要，这边填写的是apk在电脑上的路径
        desired_caps['appPackage'] = 'com.xiniunet.xntalk'  # app的包名，唯一标志app
        desired_caps['appActivity'] = 'com.xiniunet.xntalk.common.activity.splash.SplashActivity'  # 对应安卓应用的操作界面
        desired_caps['unicodeKeyboard'] = True  # 安装一个中文的输入法
        desired_caps['resetKeyboard'] = True  #
        desired_caps['noReset'] = True  # 清除元素数据，跳过初始页面
        desired_caps['newCommandTimeout'] = 6000
        # 启动Remote RPC
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)  # 把上述参数传给appium services

    def tearDown(self):
        self.driver.quit()

    def test_start(self):
        self.driver.implicitly_wait(10)
        # 输入用户名、密码
        ele = self.driver.find_element_by_id("com.xiniunet.xntalk:id/et_account")
        ele.send_keys('15370135956')
        ele = self.driver.find_element_by_id("com.xiniunet.xntalk:id/et_password")
        ele.send_keys('123456')

        time.sleep(2)
        # 点击登录
        self.driver.find_element_by_id('com.xiniunet.xntalk:id/btn_login').click()
        time.sleep(5)
        print('登录成功')

    if __name__ == '__main__':
        suite = unittest.TestLoader().loadTestsFromTestCase(LoginTest)

        unittest.TextTestRunner(verbosity=2).run(suite)

        with open('C:\\Users\\Administrator\\Desktop\\'+timestr+'.html','wb') as f:
            runner =HTMLTestRunner.HTMLTestRunner(stream=f,
                                                  title='MathFunc Test Report',
                                                  description='generated by HTMLTestRunner.',
                                                  verbosity=2
                                                  )
            runner.run(suite)
